### ISSUE TITLE
Missing test.ipynb

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/CarND-Term1-Starter-Kit#34]
The steps that were added to the CarND Lesson 2 to use this repository (Finding Lane Lines - Run Some Code) indicate that there should be a test.ipynb that should be run after the environment is set up to test it:

```
2. Launch the Jupyter notebook with Anaconda or Docker.
# Anaconda
source activate carnd-term1 # If currently deactivated, i.e. start of a new terminal session
jupyter notebook test.ipynb
...
3. Go to http://localhost:8888/notebooks/test.ipynb in your browser and run all the cells. Everything should execute without error.
```

This file seems to be missing.

**Comment by robsf** [comment]
I had the same problem.  However, poking around the CarND-Term1-Starter-Kit page I found a test.ipynb file and downloaded.  I can't find the file now on the page (had to reboot my computer - something else I was doing hung my machine), but I'm attaching it here (had to zip in order to attach).  When I try to open it in Jupyter, I get a non-JSON error, but I can open it in Chrome and grab the contents.
Hope this helps.
[test.zip](https://github.com/udacity/CarND-Term1-Starter-Kit/files/674601/test.zip)

**Comment by domluna** [comment]
Are you sure you downloaded this repo https://github.com/udacity/CarND-Term1-Starter-Kit-Test? The names are quite similar so that could be the confusion.

1. Clone and navigate to the starter kit test repository.
```sh
git clone https://github.com/udacity/CarND-Term1-Starter-Kit-Test.git
cd CarND-Term1-Starter-Kit-Test
```

**Comment by brahmwindeler** [comment]
Good catch! Even after you posted the link I had to double check the names. I missed the "-Test" at the end of the name. That was the issue.
